# Generated by Django 5.0.4 on 2024-04-26 17:44

import expenses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetcategory',
            name='date',
            field=models.DateField(default=expenses.models.default_date),
        ),
    ]
