# Generated by Django 4.2.1 on 2023-09-20 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensereport',
            name='title',
            field=models.CharField(default='test', max_length=128),
            preserve_default=False,
        ),
    ]
