# Generated by Django 5.0.1 on 2024-03-09 23:55

import django.db.models.deletion
import expenses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensereport',
            name='category',
            field=models.ForeignKey(default=expenses.models.get_or_create_default_category, on_delete=django.db.models.deletion.CASCADE, to='expenses.budgetcategory'),
        ),
    ]
