# Generated by Django 4.2.1 on 2023-12-31 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expensereport_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensereport',
            name='expenseChoices',
            field=models.TextField(choices=[('RENT_MORTGAGE', 'Rent/Mortgage'), ('GAS_TRANSIT', 'Gas/Transit'), ('INCOME', 'Income'), ('TAXES', 'Taxes'), ('UTILITIES', 'Utilites'), ('GROCERIES', 'Groceries'), ('DINE_OUT', 'Dine Out'), ('ENTERTAINMENT', 'Entertainment'), ('TRAVEL', 'Travel'), ('SHOPPING', 'Shopping'), ('REPAIRS', 'Repairs'), ('HEALTHCARE', 'Healthcare'), ('GIVING', 'Giving'), ('SELF_CARE', 'Self Care'), ('MISCELLANEOUS', 'Miscellaneous')]),
        ),
    ]
