# Generated by Django 4.2.1 on 2023-05-25 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='expenseReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('expenseChoices', models.TextField(choices=[('RENT_MORTGAGE', 'Rent/Mortgage'), ('GAS_REPAIRS', 'Gas/Vehicle Repairs'), ('INCOME', 'Income'), ('TAXES', 'Taxes'), ('UTILITIES', 'Utilites'), ('GROCERIES', 'Groceries'), ('DINE_OUT', 'Dine Out'), ('ENTERTAINMENT', 'Entertainment'), ('TRAVEL', 'Travel'), ('SHOPPING', 'Shopping'), ('HOME_IMPROVEMENT', 'Home Improvement and Repairs'), ('HEALTHCARE', 'Healthcare')])),
                ('value', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('note', models.TextField(max_length=140)),
            ],
        ),
    ]
