# Generated by Django 4.2.1 on 2023-05-25 02:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensereport',
            name='date',
            field=models.DateField(verbose_name=datetime.date(2023, 5, 25)),
        ),
    ]
