# Generated by Django 4.2.1 on 2023-05-25 02:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_alter_expensereport_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensereport',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
