# Generated by Django 4.2.1 on 2023-05-25 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_alter_expensereport_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensereport',
            name='expenseChoices',
            field=models.TextField(choices=[('RENT_MORTGAGE', 'Rent/Mortgage'), ('GAS_REPAIRS', 'Gas/Vehicle Repairs'), ('INCOME', 'Income'), ('TAXES', 'Taxes'), ('UTILITIES', 'Utilites'), ('GROCERIES', 'Groceries'), ('DINE_OUT', 'Dine Out'), ('ENTERTAINMENT', 'Entertainment'), ('TRAVEL', 'Travel'), ('SHOPPING', 'Shopping'), ('HOME_IMPROVEMENT', 'Home Improvement and Repairs'), ('HEALTHCARE', 'Healthcare'), ('GIVING', 'Giving')]),
        ),
    ]
