# Generated by Django 4.2.1 on 2023-05-28 01:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='recipesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=128)),
                ('meal_type', models.TextField(choices=[('BREAKFAST', 'Breakfast'), ('LUNCH', 'Lunch'), ('DINNER', 'Dinner'), ('DESSERT', 'Dessert'), ('APPETIZER', 'Appetizer')])),
                ('ingredients', models.CharField(max_length=2000)),
                ('instructions', models.CharField(max_length=2000)),
            ],
        ),
    ]
